### ISSUE TITLE
getAccountDetails broken in Horizon 0.18.0 rc1

### ISSUE THREAD

**Issue by bartekn** [Soneso/stellar-ios-mac-sdk#66] opened 2019-06-03 18:41 UTC
Some [users](https://stellar.stackexchange.com/questions/2588/get-account-details-data-missing) report that `getAccountDetails` is broken. It's possible that it's because we've [just](https://stellarorg.statuspage.io/incidents/0dzbx4t1khgs) deployed [Horizon 0.18.0 rc1](https://github.com/stellar/go/releases/tag/horizon-v0.18.0rc1) which removes `paging_token` field (it was always empty anyway).

**Comment by christain-rogobete** [comment] 2019-06-03 20:07
Yes, thats the reason. I will fix it asap.

**Comment by christain-rogobete** [comment] 2019-06-03 20:30
Thank you @bartekn, the issue is fixed with this new release: https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/1.6.6

**Comment by bartekn** [comment] 2019-06-03 20:32
Thanks for a fast fix! 🚀

**Closed** 2019-06-03 20:51 UTC
